version: 0.0
resources:
  - reapp:
      type: AWS::ECS::TaskDefinition
      properties:
        taskDefinition:
          containerDefinitions:
            - name: propertybackend
              image: 296021958260.dkr.ecr.us-east-1.amazonaws.com/cdk-hnb659fds-container-assets-296021958260-us-east-1
              portMappings:
                - containerPort: 8000
              environment:
                - name: POSTGRES_DB
                  value: ${BACKEND_POSTGRES_NAME}
                - name: POSTGRES_USER
                  value: ${BACKEND_POSTGRES_USER}
                - name: POSTGRES_PASSWORD
                  value: ${BACKEND_POSTGRES_PASSWORD}
              essential: true
