version: 0.2

phases:
  install:
    commands:
      - chmod -R +x scripts/
      - chmod +x .env
      - scripts/docker_login.sh

  pre_build:
    commands:
      - scripts/test/pre_test.sh

  build:
    commands:
      - scripts/test/run_tests.sh
