version: '3'
services:

  propertysqldb:
    image: postgres
    environment:
      - POSTGRES_DB=${BACKEND_POSTGRES_NAME}
      - POSTGRES_USER=${BACKEND_POSTGRES_USER}
      - POSTGRES_PASSWORD=${BACKEND_POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  propertybackend:
    image: diddyinnovtion/reapp:latest
    container_name: propertybackend
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "80:8000"
    links:
      - propertysqldb
    volumes:
      - ./:/usr/src/reapp
      - ./static/:/usr/src/reapp/static
      - ./static/:/usr/src/reapp/staticfiles
    command: >
      sh -c "python3 manage.py migrate &&
             chmod +x ./scripts/create_superuser.sh &&
             /bin/sh -c './scripts/create_superuser.sh' &&
             python3 manage.py runserver 0.0.0.0:8000"
    stdin_open: true
    tty: true
    depends_on:
      - propertysqldb

volumes:
  postgres_data:

