version: '3'
services:

  propertysqldb:
    image: postgres
    environment:
      - POSTGRES_DB=${BACKEND_POSTGRES_NAME}
      - POSTGRES_USER=${BACKEND_POSTGRES_USER}
      - POSTGRES_PASSWORD=${BACKEND_POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  propertybackend:
    image: diddyinnovtion/reapp:latest
    container_name: propertybackend
    env_file: .env
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:8000"
    links:
      - propertysqldb
    volumes:
      - ./:/usr/src/app
      - ./static/:/usr/src/app/static
      - ./static/:/usr/src/app/staticfiles
    command: sh -c "python3 manage.py migrate && chmod +x create_superuser.sh && /bin/sh -c './create_superuser.sh' && python3 manage.py runserver 0.0.0.0:8000"
    stdin_open: true
    tty: true
    depends_on:
      - propertysqldb

volumes:
  postgres_data:

